/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import calendar from "@offset-dev/strapi-calendar/strapi-admin";
import encryptableField from "strapi-plugin-encryptable-field/strapi-admin";
import netlifyDeployments from "strapi-plugin-netlify-deployments/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    calendar: calendar,
    "encryptable-field": encryptableField,
    "netlify-deployments": netlifyDeployments,
  },
});
